### ISSUE TITLE
Content in the editor is in one line

### ISSUE THREAD

**Issue by TecDesign** [codehoose/real-world-map-data#6] opened 2019-10-07 08:11 UTC
When opening the Real World Map Data project and select a converted osm to txt file, the materials, and import the map file, i get the following error.

FormatException: Input string was not in a correct format.
System.Number.ParseSingle (System.String value, System.Globalization.NumberStyles options, System.Globalization.NumberFormatInfo numfmt)  etc etc..

When using the NY text file out of the Scene Based Real World Map Data it will import the map data, but the content will be shown in the editor in one line, see picture below. 
It makes no difference if the project is opend in Unity 2018.3.11f1 or Unity 2019.1.13f1. 

![osm 1](https://user-images.githubusercontent.com/6989468/66302025-7ee54980-e8f8-11e9-9531-c28b148517d7.JPG)

![OSM](https://user-images.githubusercontent.com/6989468/66302010-7987ff00-e8f8-11e9-9480-6af885ec8634.JPG)

**Comment by logfireMarco** [comment] 2020-10-14 15:00
The error could be caused by the CultureInfo in CSharp. In the BaseOSM.cs file:
before: 
 ... instance = (T)Convert.ChangeType(strValue, typeof(T)); ...
after:
... instance = (T)Convert.ChangeType(strValue, typeof(T), new CultureInfo("en-US")); ...

don't forget to add "using System.Globalization"

**Comment by VendaarDev** [comment] 2021-07-28 13:49
I cant find any line saying "instance = (T)Convert.ChangeType(strValue, typeof(T))" in BaseOsm.cs

**Comment by codehoose** [comment] 2023-11-24 17:20
This might be fixed by a PR for issue 5. Please get latest. Note that the default branch is now `main`.

**Closed as completed by codehoose** 2023-11-24 17:20 UTC
